# Install Rest client extension in vs code to hit api's directly from here 

# @serverUrl = http://localhost:1001/
@serverUrl = https://bookbyte-dcfk.onrender.com
@baseUrl = {{serverUrl}}/api


# ========== Auth ===========
# sing up
POST {{baseUrl}}/sign-up
Content-Type: application/json

{
    "username": "newtest",
    "email":"newtest@gmail.com",
    "password":"newtest",
    "address":"dont know"
}

###
# sing in
POST {{baseUrl}}/sign-in 
Content-Type: application/json

{
    "username": "admin",
    "password":"admin"
}
###

# ============ Admin apis =========

# use these credentials to perform admin operations
# {
#     "username": "admin",
#     "password":"admin",
# }

# add book 
POST {{baseUrl}}/add-book
Content-Type: application/json
id: admin_id_here
Authorization: Bearer admin_token_here

{
    "url": "https://example.com/book1.jpg",
    "title": "good Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "price": 299,
    "desc": "A classic novel set in the 1920s exploring themes of wealth and society.",
    "language": "English"
}

###
# update book info
PUT {{baseUrl}}/update-book
Content-Type: application/json
id: admin_id_here
bookId: your_book_id
Authorization: Bearer admin_token_here

# update values -> any number of changes
{
    "url": "https://example.com/book1.jpg",
    "title": "good at Gatsby",
    "author": "F. Scott Fitzgerald",
    "price": 299,
    "desc": "A classic novel set in the 1920s exploring themes of wealth and society.",
    "language": "Eish"
}
###

# delete book
DELETE {{baseUrl}}/delete-book
id: admin_id_here
bookId: your_book_id
Authorization: Bearer admin_token_here
###


#  ============= Common Api's [User, Admin] ======================

# get user or admin info
GET {{baseUrl}}/get-user-information
id: user_id
Authorization: Bearer user_token_here
###

PUT {{baseUrl}}/update-address
Content-Type: application/json
id: user_id
Authorization: Bearer user_token_here

{
    "address":"new_address_here"
}
###
# to get all the books
GET {{baseUrl}}/get-all-books

###

# get book by id
GET {{baseUrl}}/get-book-by-id/:bookId 

###
